/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Domain;

import Logic.CombatSystem;

/**
 *
 * @author eduar
 */
public class AddPartsMenu extends javax.swing.JFrame {

    CombatSystem pSystem;
    MainMenu menu;
    public AddPartsMenu(CombatSystem pSystem, MainMenu menu) {
        initComponents();
        this.pSystem = pSystem;
        this.menu = menu;
        boxTipo.addItem("P");
        boxTipo.addItem("B");
        boxTipo.addItem("T");
        boxTipo.addItem("C");
        boxTipo.addItem("Arma");
        boxRareza.addItem("PP");
        boxRareza.addItem("PE");
        boxRareza.addItem("PC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textVida = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        textVelocidad = new javax.swing.JTextPane();
        boxTipo = new javax.swing.JComboBox<>();
        boxRareza = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAtaque = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        textNombre = new javax.swing.JTextPane();
        buttonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelAtaque = new javax.swing.JLabel();
        buttonAnadir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(textVida);

        jScrollPane2.setViewportView(textVelocidad);

        boxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoActionPerformed(evt);
            }
        });

        textArea1.setEditable(false);
        textArea1.setColumns(20);
        textArea1.setRows(5);
        jScrollPane3.setViewportView(textArea1);

        jScrollPane4.setViewportView(textAtaque);

        jScrollPane5.setViewportView(textNombre);

        buttonRegresar.setText("Regresar");
        buttonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Vida");

        jLabel3.setText("Velocidad");

        labelAtaque.setText("Ataque");

        buttonAnadir.setText("Añadir");
        buttonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnadirActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de pieza");

        jLabel6.setText("(C)Cabeza");

        jLabel7.setText("(B)Brazos");

        jLabel8.setText("(P)Piernas");

        jLabel9.setText("(T)Torax");

        jLabel10.setText("Rareza de la pieza");

        jLabel12.setText("(PC)Pieza Comun");

        jLabel13.setText("(PE)Pieza Estandar");

        jLabel14.setText("(PP)Pieza Premiun");

        jLabel4.setText("*La rareza no aplica en las armas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonRegresar)
                                .addGap(27, 27, 27)
                                .addComponent(buttonAnadir))
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5)
                                .addComponent(boxRareza, 0, 133, Short.MAX_VALUE)
                                .addComponent(boxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane4))
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(labelAtaque)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxRareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonRegresar)
                        .addComponent(buttonAnadir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAtaque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoActionPerformed
        if(boxTipo.getSelectedItem().equals("Arma"))
        {
            labelAtaque.setText("Daño");
        }else
        {
            labelAtaque.setText("Ataque");
        }
        
        if(boxTipo.getSelectedItem().equals("C")||boxTipo.getSelectedItem().equals("P")||boxTipo.getSelectedItem().equals("T"))
        {
            textAtaque.setEditable(false);
        }
        else {
        	textAtaque.setEditable(true);
        }
        if(boxTipo.getSelectedItem().equals("B")||boxTipo.getSelectedItem().equals("P")||boxTipo.getSelectedItem().equals("Arma"))
        {
            textVida.setEditable(false);
        }
        else {
        	textVida.setEditable(true);
        }
        if(boxTipo.getSelectedItem().equals("B")||boxTipo.getSelectedItem().equals("T"))
        {
            textVelocidad.setEditable(false);
        }
        else {
        	textVelocidad.setEditable(true);
        }
    }//GEN-LAST:event_boxTipoActionPerformed

    private void buttonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegresarActionPerformed
        setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_buttonRegresarActionPerformed

    private void buttonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnadirActionPerformed

        switch(boxTipo.getItemAt(boxTipo.getSelectedIndex()))
        {
            case("C"):
                if(!textVelocidad.getText().equals("")&&!textVida.getText().equals("")&&!textNombre.getText().equals(""))
                {
                    if(pSystem.addhead("C",textNombre.getText(), boxRareza.getItemAt(boxRareza.getSelectedIndex()), Integer.parseInt(textVelocidad.getText()), Integer.parseInt(textVida.getText())))
                    {
                        textArea1.setText("Cabeza añadida");
                    }
                }else
                {
                    textArea1.setText("Campo Nombre, Vida o Velocidad vacios");
                }
                break;
            case("B"):
                if(!textNombre.getText().equals("")&&!textAtaque.getText().equals(""))
                {
                    if(pSystem.addArms("B", textNombre.getText(), boxRareza.getItemAt(boxRareza.getSelectedIndex()), Integer.parseInt(textAtaque.getText())))
                    {
                        textArea1.setText("Brazos añadidos");
                    }
                }else
                {
                    textArea1.setText("Campo Nombre o Ataque vacios");
                }
                
                break;
            case("P"):
                if(!textVelocidad.getText().equals("")&&!textNombre.getText().equals(""))
                {
                    if(pSystem.addLegs("P", textNombre.getText(), boxRareza.getItemAt(boxRareza.getSelectedIndex()), Integer.parseInt(textVelocidad.getText())))
                    {
                        textArea1.setText("Piernas añadidas");
                    }
                }else
                {
                    textArea1.setText("Campo Nombre o Velocidad vacios");
                }
                
                break;
            case("T"):
                if(!textVida.getText().equals("")&&!textNombre.getText().equals(""))
                {
                    if(pSystem.addChest("T", textNombre.getText(), boxRareza.getItemAt(boxRareza.getSelectedIndex()), Integer.parseInt(textVida.getText())))
                    {
                        textArea1.setText("Torax añadido");
                    }
                }else
                {
                    textArea1.setText("Campo Nombre o Vida vacios");
                }
                
                break;
            case("Arma"):
                if(!textVelocidad.getText().equals("")&&!textAtaque.getText().equals("")&&!textNombre.getText().equals(""))
                {
                    if(pSystem.addGun(textNombre.getText(), Integer.parseInt(textAtaque.getText()), Integer.parseInt(textVelocidad.getText())))
                    {
                        textArea1.setText("Arma añadida");
                    }
                }else
                {
                    textArea1.setText("Campo Nombre, Daño o Velocidad vacios");
                }
                break;
        }
        textNombre.setText("");
        textVelocidad.setText("");
        textVida.setText("");
        textAtaque.setText("");
        boxRareza.setSelectedIndex(0);
        boxTipo.setSelectedIndex(0);
        
    }//GEN-LAST:event_buttonAnadirActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxRareza;
    private javax.swing.JComboBox<String> boxTipo;
    private javax.swing.JButton buttonAnadir;
    private javax.swing.JButton buttonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelAtaque;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JTextPane textAtaque;
    private javax.swing.JTextPane textNombre;
    private javax.swing.JTextPane textVelocidad;
    private javax.swing.JTextPane textVida;
    // End of variables declaration//GEN-END:variables
}
