/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Domain;

import Logic.CombatSystem;
import Domain.Robot;

/**
 *
 * @author eduar
 */
public class CambiarPiezasMenu extends javax.swing.JFrame {

    CombatSystem pSystem;
    MainMenu menu;
    public CambiarPiezasMenu(CombatSystem pSystem, MainMenu menu) {
        initComponents();
        this.pSystem = pSystem;
        this.menu = menu;
        boxRobot.addItem("");
        for(Robot robot : pSystem.getHumanRobotList())
        {
            boxRobot.addItem(robot.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxCabeza = new javax.swing.JComboBox<>();
        boxBrazos = new javax.swing.JComboBox<>();
        boxTorax = new javax.swing.JComboBox<>();
        boxPiernas = new javax.swing.JComboBox<>();
        boxRobot = new javax.swing.JComboBox<>();
        buttonAceptar = new javax.swing.JButton();
        buttonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textArea1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea2 = new javax.swing.JTextArea();
        boxArmas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boxRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRobotActionPerformed(evt);
            }
        });

        buttonAceptar.setText("Aceptar");
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarActionPerformed(evt);
            }
        });

        buttonRegresar.setText("Regrasar");
        buttonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Robot");

        jLabel2.setText("Cabeza");

        jLabel3.setText("Brazos");

        jLabel4.setText("Torax");

        jLabel5.setText("Piernas");

        jLabel6.setText("Al seleccionar un robot automaticamente se ");

        jLabel7.setText("seleccionaran sus piezas");

        textArea2.setEditable(false);
        textArea2.setColumns(20);
        textArea2.setRows(5);
        jScrollPane1.setViewportView(textArea2);

        jLabel8.setText("Arma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(textArea1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(boxRobot, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxCabeza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxBrazos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxTorax, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxPiernas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel2))
                            .addComponent(boxArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel8)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textArea1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxRobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxCabeza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(boxBrazos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(boxTorax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(boxPiernas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(boxArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(buttonAceptar)
                .addGap(18, 18, 18)
                .addComponent(buttonRegresar)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRobotActionPerformed
        loadParts(pSystem);
    }//GEN-LAST:event_boxRobotActionPerformed
    
    private void loadParts(CombatSystem pSystem)
    {
    	boxCabeza.removeAllItems();
    	boxBrazos.removeAllItems();
    	boxTorax.removeAllItems();
    	boxPiernas.removeAllItems();
        boxArmas.removeAllItems();
        for(Robot robot : pSystem.getHumanRobotList())
        {
            if(robot.getName().equals((String)boxRobot.getSelectedItem()))
            {
                boxCabeza.addItem(robot.getHead());
                boxBrazos.addItem(robot.getArms());
                boxTorax.addItem(robot.getChest());
                boxPiernas.addItem(robot.getLegs());
                boxArmas.addItem(robot.getGun());
                break;
            }
        }
        if(!boxRobot.getSelectedItem().equals(""))
        {
            for(Part part : pSystem.getPartList())
            {
                    if(!boxCabeza.getSelectedItem().equals(part.getName())&&!boxBrazos.getSelectedItem().equals(part.getName())&&!boxTorax.getSelectedItem().equals(part.getName())&&!boxPiernas.getSelectedItem().equals(part.getName()))
                    {
                        switch(part.getType())
                        {
                            case("C"):
                                boxCabeza.addItem(part.getName());
                                break;
                            case("B"):
                                boxBrazos.addItem(part.getName());
                                break;
                            case("T"):
                                boxTorax.addItem(part.getName());
                                break;
                            case("P"):
                                boxPiernas.addItem(part.getName());
                                break;
                        }
                    }
                }
            for(Gun gun : pSystem.getGunList())
            {
                if(!boxArmas.getSelectedItem().equals(gun.getName()))
                {
                    boxArmas.addItem(gun.getName());
                }
            }
        }
        
    }
    
    private void buttonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegresarActionPerformed
        setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_buttonRegresarActionPerformed

    private void buttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarActionPerformed
    	HumanRobot temporalRobot= null;
        
        
        if(!boxRobot.getSelectedItem().equals(""))
        {
            for(HumanRobot robot : pSystem.getHumanRobotList())
            {
                if(robot.getName().equals(boxRobot.getSelectedItem()))
                {
                    temporalRobot = robot;
                    break;
                }
            }
            temporalRobot.setHead((String)boxCabeza.getSelectedItem());
            temporalRobot.setArms((String)boxBrazos.getSelectedItem());
            temporalRobot.setChest((String)boxTorax.getSelectedItem());
            temporalRobot.setLegs((String)boxPiernas.getSelectedItem());
            temporalRobot.setGun((String)boxArmas.getSelectedItem());
            
            textArea2.setText("Piezas cambiadas");
        }else
        {
            textArea2.setText("Seleccione un robot");
        }
    }//GEN-LAST:event_buttonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxArmas;
    private javax.swing.JComboBox<String> boxBrazos;
    private javax.swing.JComboBox<String> boxCabeza;
    private javax.swing.JComboBox<String> boxPiernas;
    private javax.swing.JComboBox<String> boxRobot;
    private javax.swing.JComboBox<String> boxTorax;
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JButton buttonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textArea1;
    private javax.swing.JTextArea textArea2;
    // End of variables declaration//GEN-END:variables
}
