/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Domain;

import Logic.CombatSystem;
import java.util.Iterator;
import javax.swing.DefaultListModel;

/**
 *
 * @author eduar
 */
public class EnsamblarRobotMenu extends javax.swing.JFrame {

    CombatSystem pSystem;
    MainMenu menu;
    public EnsamblarRobotMenu(CombatSystem pSystem, MainMenu menu) {
        initComponents();
        this.pSystem = pSystem;
        this.menu = menu;
        Iterator it1 = pSystem.getPartList().iterator();
        boxCabeza.addItem("");
        boxBrazos.addItem("");
        boxTorax.addItem("");
        boxPiernas.addItem("");
        boxArma.addItem("");
        while(it1.hasNext())
        {
            Part part = (Part) it1.next();
            switch(part.getType())
            {
                case("C"):
                    boxCabeza.addItem(part.getName());
                    break;
                case("B"):
                    boxBrazos.addItem(part.getName());
                    break;
                case("T"):
                    boxTorax.addItem(part.getName());
                    break;
                case("P"):
                    boxPiernas.addItem(part.getName());
                    break;
            }
        }
        for (Gun gun : pSystem.getGunList())
        {
            boxArma.addItem(gun.getName());
        }
        
       loadTeamsPilots(pSystem);
    }
    
    private void loadTeamsPilots(CombatSystem pSystem)
    {
    	 DefaultListModel teamsModel = new DefaultListModel();
         for (String team : pSystem.getTeamsList())
         {
             teamsModel.addElement(team);
         }
         
         DefaultListModel pilotsModel = new DefaultListModel();
         for (String pilot : pSystem.getPilotsList())
         {
             pilotsModel.addElement(pilot);
         }
         listTeams.setModel(teamsModel);
         listPilotos.setModel(pilotsModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxCabeza = new javax.swing.JComboBox<>();
        boxBrazos = new javax.swing.JComboBox<>();
        boxTorax = new javax.swing.JComboBox<>();
        boxPiernas = new javax.swing.JComboBox<>();
        textNombreRobot = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTeams = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPilotos = new javax.swing.JList<>();
        buttonRegresar = new javax.swing.JButton();
        buttonEnsamblar = new javax.swing.JButton();
        textTeam = new javax.swing.JTextField();
        textNombrePiloto = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        boxArma = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listTeams);

        jScrollPane2.setViewportView(listPilotos);

        buttonRegresar.setText("Regrasar");
        buttonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegresarActionPerformed(evt);
            }
        });

        buttonEnsamblar.setText("Ensamblar");
        buttonEnsamblar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnsamblarActionPerformed(evt);
            }
        });

        textArea1.setEditable(false);
        textArea1.setColumns(20);
        textArea1.setRows(5);
        jScrollPane3.setViewportView(textArea1);

        jLabel1.setText("Cabeza");

        jLabel2.setText("Brazos");

        jLabel3.setText("Piernas");

        jLabel4.setText("Torax");

        jLabel5.setText("Nombre");

        jLabel6.setText("Piloto");

        jLabel7.setText("Equipo");

        jLabel8.setText("Lista de equipos");

        jLabel9.setText("Lista de pilotos");

        jLabel10.setText("Si el piloto o equipo");

        jLabel11.setText("ingresado no esta en ");

        jLabel12.setText("la lista, se tomara");

        jLabel13.setText("como nuevo");

        jLabel14.setText("Arma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEnsamblar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)
                        .addComponent(boxCabeza, 0, 120, Short.MAX_VALUE)
                        .addComponent(textNombreRobot))
                    .addComponent(buttonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxBrazos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(boxTorax, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(textNombrePiloto, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(boxArma, 0, 120, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addComponent(boxPiernas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxCabeza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxBrazos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxTorax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxPiernas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombreRobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNombrePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(buttonEnsamblar)
                            .addGap(36, 36, 36)
                            .addComponent(buttonRegresar)
                            .addGap(36, 36, 36))))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegresarActionPerformed
        setVisible(false);
        this.menu.setVisible(true);
    }//GEN-LAST:event_buttonRegresarActionPerformed

    private void buttonEnsamblarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnsamblarActionPerformed
        if(!boxCabeza.getSelectedItem().equals("")&&!boxBrazos.getSelectedItem().equals("")&&!boxPiernas.getSelectedItem().equals("")&&!boxTorax.getSelectedItem().equals("")&&!boxArma.getSelectedItem().equals(""))
        {
            if(!textNombreRobot.getText().equals("")&&!textTeam.getText().equals("")&&!textNombrePiloto.getText().equals(""))
            {
                pSystem.addHumanRobot(textNombreRobot.getText(), (String)boxArma.getSelectedItem(), (String)boxPiernas.getSelectedItem(), (String)boxBrazos.getSelectedItem(), (String)boxTorax.getSelectedItem(), (String)boxCabeza.getSelectedItem(), "H", textNombrePiloto.getText(), textTeam.getText());
                textArea1.setText("Robot Ensamblado");
                boxCabeza.setSelectedIndex(0);
                boxBrazos.setSelectedIndex(0);
                boxArma.setSelectedIndex(0);
                boxPiernas.setSelectedIndex(0);
                boxTorax.setSelectedIndex(0);
                textNombreRobot.setText("");
                textNombrePiloto.setText("");
                textTeam.setText("");
                loadTeamsPilots(pSystem);
                
            }else
            {
                textArea1.setText("Nombre del robot, Equipo o Nombre del piloto no ingresado");
            }
        }else
        {
            textArea1.setText("Cabeza, Brazos, Torax, Piernas o Arma sin seleccionar");
        }
    }//GEN-LAST:event_buttonEnsamblarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxArma;
    private javax.swing.JComboBox<String> boxBrazos;
    private javax.swing.JComboBox<String> boxCabeza;
    private javax.swing.JComboBox<String> boxPiernas;
    private javax.swing.JComboBox<String> boxTorax;
    private javax.swing.JButton buttonEnsamblar;
    private javax.swing.JButton buttonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listPilotos;
    private javax.swing.JList<String> listTeams;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JTextField textNombrePiloto;
    private javax.swing.JTextField textNombreRobot;
    private javax.swing.JTextField textTeam;
    // End of variables declaration//GEN-END:variables
}
