/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Domain;

import java.awt.Window;
import java.awt.event.WindowStateListener;
import java.io.IOException;

import javax.swing.WindowConstants;

import Logic.CombatSystem;

/**
 *
 * @author eduar
 */
public class MainMenu extends javax.swing.JFrame
{
    private static final long serialVersionUID = 1L;
	CombatSystem pSystem;
    
    
    public MainMenu(CombatSystem pSystem)
    {
        this.pSystem = pSystem;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonIniciarSimulacion = new javax.swing.JButton();
        buttonAnadirPiezas = new javax.swing.JButton();
        buttonEnsamblarRobot = new javax.swing.JButton();
        buttonCambiarPiezasRobot = new javax.swing.JButton();
        buttonMostrarEstadisticasRobots = new javax.swing.JButton();
        buttonMostrarRobotPorPiloto = new javax.swing.JButton();
        buttonMostrarRobotsPorEquipo = new javax.swing.JButton();
        buttonMostrarEstadisticasDeVictorias = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonIniciarSimulacion.setText("Iniciar la simulación");
        buttonIniciarSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIniciarSimulacionActionPerformed(evt);
            }
        });

        buttonAnadirPiezas.setText("Añadir piezas");
        buttonAnadirPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnadirPiezasActionPerformed(evt);
            }
        });

        buttonEnsamblarRobot.setText("Ensamblar robot");
        buttonEnsamblarRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnsamblarRobotActionPerformed(evt);
            }
        });

        buttonCambiarPiezasRobot.setText("Cambiar piezas del robot");
        buttonCambiarPiezasRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCambiarPiezasRobotActionPerformed(evt);
            }
        });

        buttonMostrarEstadisticasRobots.setText("Estadísticas de robots");
        buttonMostrarEstadisticasRobots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarEstadisticasRobotsActionPerformed(evt);
            }
        });

        buttonMostrarRobotPorPiloto.setText("Mostrar los robots que son manejados por un piloto");
        buttonMostrarRobotPorPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarRobotPorPilotoActionPerformed(evt);
            }
        });

        buttonMostrarRobotsPorEquipo.setText("Mostrar robots que están en el equipo ingresado");
        buttonMostrarRobotsPorEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarRobotsPorEquipoActionPerformed(evt);
            }
        });

        buttonMostrarEstadisticasDeVictorias.setText("Ver las estadísticas de victorias ganadas por la humanidad");
        buttonMostrarEstadisticasDeVictorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMostrarEstadisticasDeVictoriasActionPerformed(evt);
            }
        });

        buttonSalir.setText("Guardar y Salir");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					buttonSalirActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMostrarEstadisticasDeVictorias, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(buttonMostrarRobotsPorEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMostrarRobotPorPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMostrarEstadisticasRobots, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCambiarPiezasRobot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEnsamblarRobot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonAnadirPiezas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonIniciarSimulacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(buttonIniciarSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAnadirPiezas)
                .addGap(18, 18, 18)
                .addComponent(buttonEnsamblarRobot)
                .addGap(18, 18, 18)
                .addComponent(buttonCambiarPiezasRobot)
                .addGap(18, 18, 18)
                .addComponent(buttonMostrarEstadisticasRobots)
                .addGap(18, 18, 18)
                .addComponent(buttonMostrarRobotPorPiloto)
                .addGap(18, 18, 18)
                .addComponent(buttonMostrarRobotsPorEquipo)
                .addGap(18, 18, 18)
                .addComponent(buttonMostrarEstadisticasDeVictorias)
                .addGap(18, 18, 18)
                .addComponent(buttonSalir)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEnsamblarRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnsamblarRobotActionPerformed
        EnsamblarRobotMenu menu = new EnsamblarRobotMenu(pSystem,this);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonEnsamblarRobotActionPerformed

    private void buttonIniciarSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIniciarSimulacionActionPerformed
        SimulationMenu menu = new SimulationMenu(pSystem,this);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonIniciarSimulacionActionPerformed

    private void buttonAnadirPiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnadirPiezasActionPerformed
       AddPartsMenu menu = new AddPartsMenu(pSystem, this);
       menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonAnadirPiezasActionPerformed

    private void buttonCambiarPiezasRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCambiarPiezasRobotActionPerformed
        CambiarPiezasMenu menu = new CambiarPiezasMenu(pSystem, this);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonCambiarPiezasRobotActionPerformed

    private void buttonMostrarEstadisticasRobotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarEstadisticasRobotsActionPerformed
        EstadisticasRobotsMenu menu = new EstadisticasRobotsMenu(pSystem, this);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonMostrarEstadisticasRobotsActionPerformed

    private void buttonMostrarRobotPorPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarRobotPorPilotoActionPerformed
        RobotsPorPilotoMenu menu = new RobotsPorPilotoMenu(pSystem, this);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonMostrarRobotPorPilotoActionPerformed

    private void buttonMostrarRobotsPorEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarRobotsPorEquipoActionPerformed
        RobotsPorEquipo menu = new RobotsPorEquipo(pSystem, this);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonMostrarRobotsPorEquipoActionPerformed

    private void buttonMostrarEstadisticasDeVictoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMostrarEstadisticasDeVictoriasActionPerformed
        HumanVictoriesMenu menu = new HumanVictoriesMenu(pSystem, this);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonMostrarEstadisticasDeVictoriasActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_buttonSalirActionPerformed
        pSystem.exitSystem();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        System.exit(0);
    }//GEN-LAST:event_buttonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnadirPiezas;
    private javax.swing.JButton buttonCambiarPiezasRobot;
    private javax.swing.JButton buttonEnsamblarRobot;
    private javax.swing.JButton buttonIniciarSimulacion;
    private javax.swing.JButton buttonMostrarEstadisticasDeVictorias;
    private javax.swing.JButton buttonMostrarEstadisticasRobots;
    private javax.swing.JButton buttonMostrarRobotPorPiloto;
    private javax.swing.JButton buttonMostrarRobotsPorEquipo;
    private javax.swing.JButton buttonSalir;
    // End of variables declaration//GEN-END:variables
}
