/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Domain;
import Logic.CombatSystem;

import java.util.Iterator;

import javax.swing.DefaultListModel;
/**
 *
 * @author eduar
 */
public class SimulationMenu extends javax.swing.JFrame {

    CombatSystem pSystem;
    MainMenu menu;
    public SimulationMenu(CombatSystem pSystem, MainMenu menu) {
        this.pSystem = pSystem;
        this.menu = menu;
        initComponents();
        Iterator<HumanRobot> it1 = pSystem.getHumanRobotList().iterator();
        while(it1.hasNext())
        {
            HumanRobot robot =(HumanRobot) it1.next();
            DefaultListModel listHuman = new DefaultListModel();
            DefaultListModel listAlien = new DefaultListModel();
            boxRobotHuman1.addItem(robot.getName());
            boxRobotHuman2.addItem(robot.getName());
            boxRobotHuman3.addItem(robot.getName());
            String[] list = pSystem.getRobotStatisctics().split(",");
            for(int a=0;a<list.length;a++)
            {
                listHuman.addElement(list[a]);
            }
            listHumanRobots.setModel(listHuman);
            list = pSystem.getAlienStatisctics().split(",");
            for(int a=0;a<list.length;a++)
            {
                listAlien.addElement(list[a]);
            }
            listAlienRobots.setModel(listAlien);
        }
        Iterator<AlienRobot> it2 = pSystem.getAlienRobotList().iterator();
        while(it2.hasNext())
        {
            AlienRobot robot =(AlienRobot) it2.next();
            boxRobotAlien1.addItem(robot.getName());
            boxRobotAlien2.addItem(robot.getName());
            boxRobotAlien3.addItem(robot.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxRobotHuman1 = new javax.swing.JComboBox<>();
        boxRobotHuman2 = new javax.swing.JComboBox<>();
        boxRobotHuman3 = new javax.swing.JComboBox<>();
        boxRobotAlien1 = new javax.swing.JComboBox<>();
        boxRobotAlien2 = new javax.swing.JComboBox<>();
        boxRobotAlien3 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAlienRobots = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listHumanRobots = new javax.swing.JList<>();
        buttonSimular = new javax.swing.JButton();
        buttonRegresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textBox1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boxRobotHuman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRobotHuman1ActionPerformed(evt);
            }
        });

        boxRobotHuman2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRobotHuman2ActionPerformed(evt);
            }
        });

        boxRobotHuman3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRobotHuman3ActionPerformed(evt);
            }
        });

        boxRobotAlien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRobotAlien1ActionPerformed(evt);
            }
        });

        boxRobotAlien2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRobotAlien2ActionPerformed(evt);
            }
        });

        boxRobotAlien3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRobotAlien3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Simularcion de Combate");

        jLabel2.setText("Alien Robots");

        jLabel3.setText("Human Robots");

        jScrollPane1.setViewportView(listAlienRobots);

        jScrollPane2.setViewportView(listHumanRobots);

        buttonSimular.setText("Simular");
        buttonSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimularActionPerformed(evt);
            }
        });

        buttonRegresar.setText("Regresar");
        buttonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegresarActionPerformed(evt);
            }
        });

        jLabel4.setText("Robot Stats");

        jLabel5.setText("Robot Stats");

        jLabel6.setText("#1");

        jLabel7.setText("#2");

        jLabel8.setText("#3");

        jLabel9.setText("#1");

        jLabel10.setText("#2");

        jLabel11.setText("#3");

        textBox1.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(boxRobotAlien3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxRobotAlien2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxRobotAlien1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(buttonSimular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(74, 74, 74))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(boxRobotHuman2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxRobotHuman3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxRobotHuman1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(45, 45, 45)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(45, 45, 45))))
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(buttonSimular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(buttonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boxRobotHuman1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boxRobotHuman2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boxRobotHuman3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boxRobotAlien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boxRobotAlien2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boxRobotAlien3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(textBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxRobotHuman2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRobotHuman2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRobotHuman2ActionPerformed

    private void boxRobotHuman3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRobotHuman3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRobotHuman3ActionPerformed

    private void boxRobotAlien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRobotAlien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRobotAlien1ActionPerformed

    private void boxRobotAlien2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRobotAlien2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRobotAlien2ActionPerformed

    private void boxRobotAlien3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRobotAlien3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRobotAlien3ActionPerformed

    private void buttonSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimularActionPerformed
        if(boxRobotHuman1.getSelectedItem().equals(boxRobotHuman2.getSelectedItem())||boxRobotHuman1.getSelectedItem().equals(boxRobotHuman3.getSelectedItem())||
                    boxRobotHuman2.getSelectedItem().equals(boxRobotHuman3.getSelectedItem())||boxRobotAlien1.getSelectedItem().equals(boxRobotAlien2.getSelectedItem())||
                    boxRobotAlien1.getSelectedItem().equals(boxRobotAlien3.getSelectedItem())||boxRobotAlien2.getSelectedItem().equals(boxRobotAlien3.getSelectedItem()))
        {
            textBox1.setText("No puede seleccionar el mismo robot 2 veces o 3 XD");
        }
        else
        {
        	textBox1.setText(pSystem.startSimulation((String)boxRobotHuman1.getSelectedItem(), (String)boxRobotHuman2.getSelectedItem(), (String)boxRobotHuman3.getSelectedItem(), (String)boxRobotAlien1.getSelectedItem(), (String)boxRobotAlien2.getSelectedItem(), (String)boxRobotAlien3.getSelectedItem()));
        	boxRobotAlien1.setSelectedIndex(0);
        	boxRobotAlien2.setSelectedIndex(0);
        	boxRobotAlien3.setSelectedIndex(0);
        	boxRobotHuman1.setSelectedIndex(0);
        	boxRobotHuman2.setSelectedIndex(0);
        	boxRobotHuman3.setSelectedIndex(0);
        }
    }//GEN-LAST:event_buttonSimularActionPerformed

    private void buttonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegresarActionPerformed
        setVisible(false);
        menu.setVisible(true);
        
    }//GEN-LAST:event_buttonRegresarActionPerformed

    private void boxRobotHuman1ActionPerformed(java.awt.event.ActionEvent evt) {
 
    }                                              

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxRobotAlien1;
    private javax.swing.JComboBox<String> boxRobotAlien2;
    private javax.swing.JComboBox<String> boxRobotAlien3;
    private javax.swing.JComboBox<String> boxRobotHuman1;
    private javax.swing.JComboBox<String> boxRobotHuman2;
    private javax.swing.JComboBox<String> boxRobotHuman3;
    private javax.swing.JButton buttonRegresar;
    private javax.swing.JButton buttonSimular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listAlienRobots;
    private javax.swing.JList<String> listHumanRobots;
    private javax.swing.JTextField textBox1;
    // End of variables declaration//GEN-END:variables
}
